sudo: required
services:
  - docker

before_install:
  - docker build -t datlt88/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true datlt88/docker-react npm run test -- --coverage

language: generic